on: push

jobs:
    convert_via_pandoc:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: docker://pandoc/core
          with:
              args: -s index.html -o resume.tex 
        - uses: mikeal/publish-to-github-action@master
          env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
