on: push

jobs:
    convert_via_pandoc:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: docker://pandoc/core
          with:
              args: -s index.html --pdf-engine=xelatex -o resume.pdf
        - run: |
            git config user.name 'Your Name'
            git config user.email 'you@example.com'
            git add resume.tex
            git commit --allow-empty-message -m ''
            git push
