on: push

jobs:
    convert_via_pandoc:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: docker://pandoc/core
          with:
              args: -s index.html -o resume.tex 
        - run: |
            git config user.name 'Your Name'
            git config user.email 'your-username@users.noreply.github.com'
            git commit --allow-empty-message -m ''
            git push
