on: push

jobs:
    convert_via_pandoc:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: docker://pandoc/core
          with:
              args: -s -o resume.tex resume.html
