on: push

jobs:
    convert_via_pandoc:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: docker://pandoc/core
          with:
              args: -s index.html -o resume.tex
        - uses: xu-cheng/latex-action@v2
          with:
              root_file: resume.tex
              latexmk_use_xelatex: true
        - uses: mikeal/publish-to-github-action@master
          env:
              GITHUB_TOKEN: ${{secrets.GITHUB}}
